from .base_config import *

MODEL_NAME = "mlp_4layers"

# 4层MLP最优默认参数
BATCH_SIZE = 64
LEARNING_RATE = 1e-3
DROPOUT = 0.5
WEIGHT_DECAY = 1e-4
MAX_SENTENCE_LEN = 120
EPOCHS = 20
USE_EARLY_STOPPING = True
PATIENCE = 3
INIT_METHOD = "default"

CHECKPOINT_PATH = f"{CHECKPOINT_DIR}/mlp_4layers_best.pt"
